#!/usr/bin/env bash
#
# install all the things

DOTFILES_ROOT="$HOME/.dotfiles"
set -e

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `bootstrap` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
echo ''

#-----------------------------------------------------------------------------
# Functions
#-----------------------------------------------------------------------------

info () {
  printf "  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

link_files () {
  ln -s $1 $2
  success "linked $1 to $2"
}

clone_repo () {
  info 'checking for dotfiles repository'
  if ! [ -d $DOTFILES_ROOT ]
  then
    git clone --recursive git@github.com:petemcw/dotfiles.git ~/.dotfiles
    success 'dotfiles are cloned'
  else
    success 'looks like dotfiles already exist'
  fi
}

setup_gitconfig () {
  if ! [ -f $DOTFILES_ROOT/git/gitconfig.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" $DOTFILES_ROOT/git/gitconfig.symlink.example > git/gitconfig.symlink

    success 'gitconfig'
  fi
}

setup_osx () {
  if ! [ -f $DOTFILES_ROOT/osx/set-defaults.sh ]
  then
    info 'setup OS X'

    user ' - What is your computer name?'
    read -e osx_computername

    USERHOME=$(sed -e 's/[\/&]/\\&/g' <<<"$HOME")

    sed -e "s/COMPUTERNAME/$osx_computername/g" $DOTFILES_ROOT/osx/set-defaults.sh.example > osx/set-defaults.sh
    chmod +x $DOTFILES_ROOT/osx/set-defaults.sh

    sed -e "s/HOMEDIR/$USERHOME/g" $DOTFILES_ROOT/mysql/my.cnf.symlink.example > mysql/my.cnf.symlink

    success 'osx defaults set'
  fi
}

install_dotfiles () {
  info 'linking dotfiles'

  overwrite_all=false
  backup_all=false
  skip_all=false

  for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"

    if [ -f $dest ] || [ -d $dest ]
    then

      overwrite=false
      backup=false
      skip=false

      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
      then
        local currentSrc="$(readlink $dest)"
        if [ "$currentSrc" == "$source" ]
        then
          skip=true
        else
          user "File already exists: `basename $source`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
          read -n 1 action

          case "$action" in
            o )
              overwrite=true;;
            O )
              overwrite_all=true;;
            b )
              backup=true;;
            B )
              backup_all=true;;
            s )
              skip=true;;
            S )
              skip_all=true;;
            * )
              ;;
          esac
        fi
      fi

      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
      then
        rm -rf $dest
        success "removed $dest"
      fi

      if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
      then
        mv $dest $dest\.backup
        success "moved $dest to $dest.backup"
      fi

      if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
      then
        link_files $source $dest
      else
        success "skipped $source"
      fi

    else
      link_files $source $dest
    fi

  done
}

#-----------------------------------------------------------------------------
# Install
#-----------------------------------------------------------------------------

clone_repo
setup_gitconfig
install_dotfiles

# If on a Mac, install and setup homebrew
if [ "$(uname -s)" == "Darwin" ]
then
  native_apps=false
  setup_osx
  info "installing brews"
  if . $DOTFILES_ROOT/home/bin.symlink/dots > /tmp/dotfiles-dots 2>&1
  then
    success "brews installed"
  else
    fail "error installing brews"
  fi

  user "Run native apps installer: [y]es, [n]o?"
  read -n 1 action

  case "$action" in
    y )
      native_apps=true;;
    n )
      native_apps=false;;
    * )
      ;;
  esac

  if [ "$native_apps" == "true" ]
  then
    echo ''
    info "installing native apps"
    if . $DOTFILES_ROOT/homebrew/install-cask.sh > /tmp/dotfiles-casks 2>&1
    then
      success "native apps installed"
    else
      fail "error installing native apps"
    fi
  fi
fi

echo ''
echo '  All finished!'
