#!/bin/sh
#
# `dots` handles installation, updates, things like that. Run it periodically
# to make sure you're on the latest and greatest.

# set OS X defaults
$HOME/.dotfiles/osx/set-defaults.sh

# brew it!
$HOME/.dotfiles/homebrew/install.sh 2>&1
