#!/bin/sh
#
# Quick shortcut to an editor.
#
# USAGE:
#
#   $ e
#   # => opens the current directory in your editor
#
#   $ e .
#   $ e /usr/local
#   # => opens the specified directory in your editor

if [ "$1" = "" ] ; then
  exec $EDITOR .
else
  exec $EDITOR "$1"
fi
